### ISSUE TITLE
hey plz ans these importent question!!!! it will help me a lot if u will ans this

### ISSUE THREAD

**Issue by michele-smith** [Sandermoen/instaclone#14]
1. why u use 2 node modules in the root folder and in the client folder? can I use only one node module ??? without installing 2 times npm? :( and how can i?
2. as u used Cloudinary for image stuff can we use MySQL for images, posts, likes, comments all of stuffs?
3. did u use react for the front end??

**Comment by Sandermoen** [comment]
1. The client and the server have two different node modules folders because they are separate, the client does not need the server's dependencies and vice versa. Additionally create-react-app creates it's own node modules folder when you set up a project.
2. Cloudinary is used to host the images. MongoDB is used as the database for the project. You could always swap it out with a MySQL database, although this would take time as you would have to replace all the logic surrounding the database seeing as document based databases (MongoDB) are vastly different from relational ones (MySQL).
3. Yes, React is used for the front end.

Thanks for checking out the project!

**Comment by michele-smith** [comment]
I request you as a brother can u plz add story feature of insta clone this
week? plzz so plz update Github code so we can see how the story feature
works plzzz
