### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Orca-web** [Sandermoen/instaclone#3]
Great project, I like it very much. Could you write a more detailed installation tutorial or video tutorial？

**Comment by Sandermoen** [comment]
Hello and thank you!
Do you have any specific parts of the setup you are struggling with?

**Comment by heidongwang** [comment]
Glad to receive your reply. i'm not good at programming，so I have some strange problems.

1. Install npm dependencies using npm install. -->There is a risk warning.

![1](https://user-images.githubusercontent.com/59247295/90030732-f93be280-dcee-11ea-83c2-13d03286c1f6.png)

After, run `npm  audit fix` to fit them.

![2](https://user-images.githubusercontent.com/59247295/90030738-fb05a600-dcee-11ea-8b78-1714ac0c556d.png)

But there are new warnings:“1 vulnerability required manual review and could not be updated”

`npm  audit` for details

![3](https://user-images.githubusercontent.com/59247295/90030754-fe009680-dcee-11ea-82f1-735c4771bd18.png)


2. How do I add a domain name?

image（http://ip:3000）
![image](https://user-images.githubusercontent.com/59247295/90031357-b6c6d580-dcef-11ea-80a4-b082c48ff590.png)


3. npm run dev -->How could  I keep running both the backend and the front end？
![4](https://user-images.githubusercontent.com/59247295/90030777-0789fe80-dcef-11ea-99aa-9a530f62a74a.png)


4. I uploaded the .env file to the root directory, but I cannot see it.

My .env file is filled with the same content as the picture. I don't know if it is correct.

![image](https://user-images.githubusercontent.com/59247295/90033578-335ab380-dcf2-11ea-958e-d5ac87f1a9a2.png)

Thank you again, author!

**Comment by Joanne02** [comment]
@Sandermoen Your project is awesome.

If there is a more detailed installation tutorial, the project will be more popular.

Mastodon is a good example. It has a very detailed [installation tutorial](https://docs.joinmastodon.org/admin/install/).

**Comment by Joanne02** [comment]
Looking forward to your reply.

**Comment by Sandermoen** [comment]
> Glad to receive your reply. i'm not good at programming，so I have some strange problems.
> 
> 1. Install npm dependencies using npm install. -->There is a  warning.
> 
> ![1](https://user-images.githubusercontent.com/59247295/90030732-f93be280-dcee-11ea-83c2-13d03286c1f6.png)
> 
> After, run `npm audit fix` to fit them.
> 
> ![2](https://user-images.githubusercontent.com/59247295/90030738-fb05a600-dcee-11ea-8b78-1714ac0c556d.png)
> 
> But there is a new warnings:“1 vulnerability required manual review and could not be updated.”
> 
> `npm audit` for details
> 
> ![3](https://user-images.githubusercontent.com/59247295/90030754-fe009680-dcee-11ea-82f1-735c4771bd18.png)
> 
> 1. I uploaded the .env file to the root directory(**/www/instaclone**), but I cannot see it.
> 
> My .env file is filled with the same content as the picture. I don't know if it is correct?
> 
> ![image](https://user-images.githubusercontent.com/59247295/90033578-335ab380-dcf2-11ea-958e-d5ac87f1a9a2.png)
> 
> Thank you again, author!
> 
> 1. npm run dev. There are some  warning.
> 
> ![4](https://user-images.githubusercontent.com/59247295/90030777-0789fe80-dcef-11ea-99aa-9a530f62a74a.png)
> 
> and how could I keep running both the backend and the front end？
> 
> 1. How do I add a domain name?
> 
> image（[http://ip:3000）](http://ip:3000%EF%BC%89)
> ![image](https://user-images.githubusercontent.com/59247295/90031357-b6c6d580-dcef-11ea-80a4-b082c48ff590.png)

__1.__ The first error you're getting where it tells you there's a high severity vulnerability is actually a problem with react-scripts (https://github.com/facebook/create-react-app/issues/9469), it's an outdated dependency that they need to update so that one you do not need to worry too much about.

__2.__ The most likely problem with your .env file is that you need to remove the // before the information, here's an example of how it should look

```javascript
MONGO_URI=mongodb://localhost:27017/instaclone
JWT_SECRET=j2390jf09kjsalkj4r93
CLOUDINARY_API_KEY=fakeCloudinaryApiKey
CLOUDINARY_API_SECRET=fakeClouinaryApiSecret
CLOUDINARY_CLOUD_NAME=fakeCloudinaryCloudName
SMTP_HOST=mail.example.com
SMTP_PORT=587
EMAIL_USERNAME=example@example.com
EMAIL_PASSWORD=Password
HOME_URL=http://localhost:3000
GITHUB_CLIENT_ID=fakeGithubClientId
GITHUB_CLIENT_SECRET=fakeGithubClientSecret
```
The // is only there to illustrate that it's __commented out__ and that you need to fill in the information.

__3.__ The warning you are getting when running *npm run dev* is actually partially my fault for not including nodemon in the devDependencies in package.json. All you should have to do to remedy this issue is to simply run __npm install -g nodemon__.

__4.__ The __npm run dev__ command runs both the backend and frontend using [concurrently](https://github.com/kimmobrunfeldt/concurrently).

__5.__ To add a domain to your server all you have to do is purchase the domain of your liking from a website like [Namecheap](https://www.namecheap.com/). You would then have to configure your domain to point to your server's public ip address. I'm sure you can find some good tutorials online if you search around.

If my explaining wasn't good enough or you're still struggling, please let me know!

**Comment by Sandermoen** [comment]
> @Sandermoen Your project is awesome.
> 
> If there is a more detailed installation tutorial, the project will be more popular.
> 
> Mastodon is a good example. It has a very detailed [installation tutorial](https://docs.joinmastodon.org/admin/install/).



> @Sandermoen Your project is awesome.
> 
> If there is a more detailed installation tutorial, the project will be more popular.
> 
> Mastodon is a good example. It has a very detailed [installation tutorial](https://docs.joinmastodon.org/admin/install/).

Thanks I'm glad you like it!
I hope my last reply will clear up some of your confusion about the installation steps!

**Comment by heidongwang** [comment]
Thanks for taking the time to contribute an answer. It’s because of helpful peers like yourself that we’re able to learn together

Your answer solved my first 3 questions.

**1.  I am not sure if my `.env ` file is correct？** 

Now my `.env ` 

```
MONGO_URI=mongodb://localhost:27017/www/instaclone
JWT_SECRET=z2390jf09kjsalkj4r94
CLOUDINARY_API_KEY=44522****99
CLOUDINARY_API_SECRET=OnaiGXk7_*****-E5aWsdfHP0V0
CLOUDINARY_CLOUD_NAME=shegusi
SMTP_HOST=smtp.163.com
SMTP_PORT=465
EMAIL_USERNAME=da_vin@163.com
EMAIL_PASSWORD=HDF****
HOME_URL=http://localhost:3000
GITHUB_CLIENT_ID=d36******8fd19e9
GITHUB_CLIENT_SECRET=2cb8d61840c5c******836d8b44495d4e91
```
my root directory is `/www/instaclone`. --> `MONGO_URI=mongodb://localhost:27017/www/instaclone`

`JWT_SECRET=z2390jf09kjsalkj4r94` <--  Change to my JWT_SECRET


**2. There is  “Invalid Host Header” error?**

I have configured my domain to point to your server's public ip address.

`ping www.heidongwang.top` :

![1](https://user-images.githubusercontent.com/59247295/90087430-52d3f980-dd4f-11ea-8a4b-efed7f739c3b.PNG)


visit the site http://www.heidongwang.top:3000

![3](https://user-images.githubusercontent.com/59247295/90087931-721f5680-dd50-11ea-88a2-5b244b006eb4.png)

but visit the site http://ip:3000 -->Jump to the login page.
![2](https://user-images.githubusercontent.com/59247295/90088070-bd396980-dd50-11ea-9c77-c7de936fcf37.png)

**3. http://ip:3000-->https://www.heidongwang.top**

How to add ssl certificate? and change the port to 443 ？

**4. Other questions?**


Click to enlarge the picture

![image](https://user-images.githubusercontent.com/59247295/90088909-b4e22e00-dd52-11ea-9953-90a2990745f0.png)

**Comment by Sandermoen** [comment]
__1. I am not sure if my .env file is correct?__
Your .env file looks mostly fine to me, make sure the MONGO_URI points to the correct mongodb server. If you are running mongodb locally on the same server what you have in your file should be fine. You can also host a mongodb server for free [here](https://www.mongodb.com/).

__2. There is “Invalid Host Header” error?__
I am actually not sure what the direct cause of this problem is, as I am not an expert :). However from what I've gathered from google, it seems that the problem may be related to some firewall settings for your server? I'm sure you can find some good resources online to solve this.

__3. How to add ssl certificate? and change the port to 443?__
For adding an ssl certificate I recommend trying out [Cloudflare](https://www.cloudflare.com/). [Here's the first tutorial I came across explaining how to use cloudflare for ssl](https://pushalert.co/blog/free-ssl-easy-setup-guide/). Another alternative is using  [Let's Encrypt](https://letsencrypt.org/), though this option requires more configuration on the server side of things. [Here's a helpful tutorial for this option](https://itnext.io/node-express-letsencrypt-generate-a-free-ssl-certificate-and-run-an-https-server-in-5-minutes-a730fbe528ca). (If you were wondering, the live demo version of the website is hosted with [Heroku](https://www.heroku.com/) which automatically applies an ssl certificate).

__4. When I close the command client(xshell), the website cannot run -->How to keep it running when the client is closed__
A good option for this using the [pm2](https://www.npmjs.com/package/pm2) library which assures that your process runs forever and restarts if any crashes occur. This __daemonizes__ your process allowing you to exit out of the shell without interrupting the process.

__5. Other questions?__
The compile warnings you see are a result of missing dependencies from different [useEffect hooks](https://reactjs.org/docs/hooks-effect.html). These can safely be ignored for now, if you would like to suppress the warning you could include the below code on the lines where the warning appears.
```javascript
// eslint-disable-next-line react-hooks/exhaustive-deps
```

**Comment by heidongwang** [comment]
@Sandermoen I am very satisfied with your reply. Thank you.

**Comment by Jishi8088** [comment]
Hello @Sandermoen 
Your project is superb...but the screen mentioned is what i am getting even though it is connected to socket properly
![Screenshot from 2020-09-25 11-18-31](https://user-images.githubusercontent.com/68326989/94231187-1fc18000-ff21-11ea-9fc7-4cf59c74eaa3.png)
![Screenshot from 2020-09-25 11-09-05](https://user-images.githubusercontent.com/68326989/94231193-22bc7080-ff21-11ea-8a5a-867cbffa9283.png)


please help as soon as possible

**Comment by webkokri** [comment]
> Hello @Sandermoen Your project is superb...but the screen mentioned is what i am getting even though it is connected to socket properly ![Screenshot from 2020-09-25 11-18-31](https://user-images.githubusercontent.com/68326989/94231187-1fc18000-ff21-11ea-9fc7-4cf59c74eaa3.png) ![Screenshot from 2020-09-25 11-09-05](https://user-images.githubusercontent.com/68326989/94231193-22bc7080-ff21-11ea-8a5a-867cbffa9283.png)
> 
> please help as soon as possible

have you found any solution on it?

**Comment by Sandermoen** [comment]
Hey!
Try to clear your browsers local storage and see if that works :)

**Comment by webkokri** [comment]
Hey Sandermoen, you have done a great job. I'm facing a critical issue on installing the software on ubuntu 20 under the nginx. It's working perfectly on the localhost, but whenever installing it to the web server, facing the token=undefined.
Let me share the screenshots.
![un](https://user-images.githubusercontent.com/59289573/173034462-8bef7dd8-638c-4e82-baeb-b7c9ce7559a5.png)
![un3](https://user-images.githubusercontent.com/59289573/173034474-95db9191-ba38-4cbd-84f8-291461717105.png)
![un2](https://user-images.githubusercontent.com/59289573/173034479-fea9a12b-c9f9-4737-974e-f8b198eef1a2.png)

**Comment by Sandermoen** [comment]
Im unsure why that's happening, I think you might have to enable websocket
connections in nginx.conf

**Comment by webkokri** [comment]
I have tried with websocket but no result. I'm a bit surprised to see if I command it "RUN NPM DEV" the token is being generated even on the same server, but whenever I'm trying with "RUN NPM BUILD" it's giving the error specified above. What could be the reason?
Any Idea? @Sandermoen 
![Uploading Screenshot 2022-06-11 042555.png…]()
